### ISSUE TITLE
Tests hang sometimes

### ISSUE THREAD

**Issue by 3noch** [reflex-frp/reflex-ghci#21]
The tests seem to hang sometimes. There is probably a race condition in the tests causing this to happen. We need to *at least* put timeouts in the tests to ensure they fail instead of hang. Then, of course, we need to make sure the tests don't have race conditions or leaks.

It's worth noting that `cabal test` will wait for all *child processes* to die as well. Since our tests spawn child processes, even just leaking them can cause the tests to hang.

**Comment by ali-abrar** [comment]
There were some specific issues with GHC 8.8+ and macOS that have been resolved. If any more hangs are reproducible, let's open issues for those with whatever information we have available.
